In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
from sklearn.svm import SVC

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.model_selection import KFold

In [ ]:

pos_5289 = "/content/drive/My Drive/Pattern_Lab/npy/A.thaliana5289_pos_PseKNC.npy"
neg_5289 = "/content/drive/My Drive/Pattern_Lab/npy/A.thaliana5289_neg_PseKNC.npy"
pos_1000 = "/content/drive/My Drive/Pattern_Lab/npy/A.thaliana1000indep_pos_pseknc.npy"
neg_1000 = "/content/drive/My Drive/Pattern_Lab/npy/A.thaliana1000indep_neg_pseknc.npy"

x_train_pos = np.load(pos_5289) 
x_train_neg = np.load(neg_5289) 
x_test_pos = np.load(pos_1000) 
x_test_neg = np.load(neg_1000) 

y_train_pos = np.tile(1, 5289) 
y_train_neg = np.tile(0, 5289) 
y_test_pos = np.tile(1, 1000) 
y_test_neg = np.tile(0, 1000) 

In [ ]:
print(x_test_neg.shape)
print(y_test_neg.shape)

print(x_train_neg.shape)
print(y_train_neg.shape)


(1000, 148)
(1000,)
(5289, 148)
(5289,)


In [ ]:
print(x_test_pos)

[[0.12374657 0.2447143  0.         ... 0.         0.28043714 0.15815572]
 [0.21618302 0.42751146 0.         ... 0.08959069 0.47356738 0.31437412]
 [0.         0.         0.12385754 ... 0.1069063  0.16108934 0.16665882]
 ...
 [0.12444675 0.         0.         ... 0.41258634 0.18012623 0.25289708]
 [0.         0.         0.24723832 ... 0.         0.19048811 0.1399111 ]
 [0.         0.         0.         ... 0.31548191 0.27359258 0.09166489]]


In [ ]:
seed = 40
np.random.seed(seed)

In [ ]:
x_training = np.concatenate((x_train_pos, x_train_neg), axis= 0)
y_training = np.concatenate((y_train_pos, y_train_neg))

In [ ]:
x_test = np.concatenate((x_test_pos, x_test_neg))
y_test = np.concatenate((y_test_pos, y_test_neg))

In [ ]:
print(x_training)

[[0.         0.         0.         ... 0.70128421 0.18145461 0.26031037]
 [0.         0.         0.         ... 0.53658254 0.09725188 0.17105845]
 [0.         0.         0.4865679  ... 0.         0.22981686 0.27482245]
 ...
 [0.         0.47327029 0.16014309 ... 0.         0.27040968 0.31971512]
 [0.         0.15733268 0.31942518 ... 0.         0.2428889  0.34989653]
 [0.40192411 0.1648837  0.33475567 ... 0.09707007 0.1979871  0.3541759 ]]


In [ ]:
print(x_test.shape)
print(y_test.shape)

(2000, 66)
(2000,)


In [ ]:
print(x_training.shape)

(10578, 66)


In [ ]:
kf = KFold(n_splits=5, random_state=seed)

In [ ]:

listc=[.25,.40,.45,.30,.50,.60,.70,.80,.90,.100]
for j in listc:
  c=j
  clf = SVC(C=c,  random_state = seed)
  val_accuracy_list = []
  train_accuracy_list = []
  sum_val=0
  sum_train=0
  i = 1
  for train_index, val_index in kf.split(x_training):
    print("Fold : ",i)
    X_train, X_val = x_training[train_index], x_training[val_index]
    y_train, y_val = y_training[train_index], y_training[val_index]
    clf.fit(X_train, y_train)
    y_val_pred = clf.predict(X_val)
    val_accuracy = accuracy_score(y_val, y_val_pred)
    sum_val += val_accuracy
    val_accuracy_list.append(val_accuracy)
    y_train_pred = clf.predict(X_train)
    train_accuracy = accuracy_score(y_train, y_train_pred)
    sum_train += train_accuracy
    train_accuracy_list.append(train_accuracy)
    i += 1 
  ave_val=sum_val/5
  ave_train=sum_train/5
  print("done")
  for i in range(0, len(train_accuracy_list)):
    print("train_accuracy : ", train_accuracy_list[i], "\tVal accuracy : ", val_accuracy_list[i])
  print("train_accuracy_ave : ",ave_train,"\tval accuracy_ave:",ave_val)
  print("Value of c",c)
  
  
  

Fold :  1
Fold :  2
Fold :  3
Fold :  4
Fold :  5
done
train_accuracy :  0.9951548097376507 	Val accuracy :  0.3435727788279773
train_accuracy :  0.9644292129520208 	Val accuracy :  0.9267485822306238
train_accuracy :  0.9705743323091468 	Val accuracy :  0.9059546313799622
train_accuracy :  0.977903816613494 	Val accuracy :  0.9460992907801419
train_accuracy :  0.9745952971759423 	Val accuracy :  0.9541371158392435
train_accuracy_ave :  0.9765314937576509 	val accuracy_ave: 0.8153024798115899
Value of c 0.25
Fold :  1
Fold :  2
Fold :  3
Fold :  4
Fold :  5
done
train_accuracy :  0.9976364925549516 	Val accuracy :  0.3591682419659735
train_accuracy :  0.9814464665563697 	Val accuracy :  0.9480151228733459
train_accuracy :  0.981564641928622 	Val accuracy :  0.9258034026465028
train_accuracy :  0.9878293749261491 	Val accuracy :  0.9569739952718677
train_accuracy :  0.9841663712631454 	Val accuracy :  0.9650118203309692
train_accuracy_ave :  0.9865286694458476 	val accuracy_ave: 0.83099